pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from pypro.base.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

rango/base/urls.py
from django.urls import path

from rango.base import views

app_name = 'base'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('add_page/', views.add_page, name='add_page')
]

rango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rango.base.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

rango/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

rango/rangomain/models.py
from django.db import models
from django.urls import reverse

from ordered_model.models import OrderedModel
from django.utils.text import slugify


class Category(OrderedModel):
    name = models.CharField(max_length=64)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta(OrderedModel.Meta):
        verbose_name_plural = 'categories'
        ordering = ('name',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('base:show_category', kwargs={'slug': self.slug})


class Page(OrderedModel):
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=64)
    url = models.URLField()
    views = models.IntegerField(default=0)
    order_with_respect_to = 'category'

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

rango/base/forms.py
from django import forms
from django.forms import TextInput

from rango.rangomain.models import Category, Page


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    titulo = forms.CharField(max_length=128,
                             help_text="Please enter the page name.")
    url = forms.URLField(max_length=200,
                         help_text="please enter the URL of the page",
                         widget=TextInput)
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    category = forms.ModelChoiceField(queryset=Category.objects.all())

    def clean(self):
        cleaned_data = super().clean()
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url += 'http://'
            cleaned_data['url'] = url

        return self.cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        fields = ('titulo', 'url', 'views', 'category')

rango/base/views.py
# Create your views here.
from django.shortcuts import render

from rango.base import facade
from rango.base.forms import CategoryForm, PageForm


def home(request):
    categories = facade.listar_categorias_ordenadas_likes()
    pages = facade.listar_pages_ordenadas_views()
    return render(request, 'base/home.html', context={'pages': pages, 'categories': categories})


def show_category(request, slug):
    category = facade.encontrar_categorias(slug)
    pages = facade.listar_paginas_de_category_ordenadas(category)
    return render(request, 'base/category.html', context={'category': category, 'pages': pages})


def add_category(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CategoryForm(request.POST)
        # check whether it's valid:
        if form.is_valid():

            form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return home(request)

        else:
            print(form.errors)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = CategoryForm()

    return render(request, 'base/add_category.html', {'form': form})


def add_page(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PageForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.clean()
            form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return home(request)

        else:
            print(form.errors)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PageForm()

    return render(request, 'base/add_page.html', {'form': form})

rango/rangomain/views.py
# Create your views here.

rango/base/templates/base/add_category.html
{% extends 'base/base.html' %}
{% block title_block %}
ADD Category
{% endblock %}

{% block body_block %}
<h1>Add a Category</h1>
<div>
    <form id="category_form" method="post" action="/add_category/">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="submit" value="Create Category"/>
    </form>
</div>
{% endblock %}

rango/base/templates/base/add_page.html
{% extends 'base/base.html' %}
{% block title_block %}
ADD page
{% endblock %}
{% block body_block %}
<h1>Add a Page</h1>
<div>
    <form id="category_form" method="post" action="/add_page/">
        {% csrf_token %}
            {{ form }}
        <input type="submit" name="submit" value="Create Page"/>
    </form>
</div>
{%  endblock %}

rango/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango -
        {% block title_block %}
        How to tango with Django!
        {% endblock %}
    </title>
</head>
<body>
<div>
    {% block body_block %}
    this is body block default content.
    {% endblock %}
</div>
<hr />
<div>
    <ul>
        <li><a href="#">About</a><br/></li>
        <li><a href="{% url 'base:add_category' %}">Add Category</a></li>
        <li><a href="{% url 'base:add_page' %}">Add Page</a></li>
        <li><a href="{% url 'base:home' %}">Home</a></li>
    </ul>
</div>
    {% block body_end_block %}
    {% endblock %}
</body>
</html>

rango/base/templates/base/category.html
{% extends 'base/base.html' %}
{% block title_block %}
{{ category.name }}
{% endblock %}
{% block body_block %}
<div>
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.titulo }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}
    {% else %}
    The specified category does not exist!
    {% endif %}
{% endblock %}
</div>

rango/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block body_block %}
<div>
    <h1>Top 5 liked categories</h1>
    <ul>
        {% for category in categories %}
        <li>
            <a href="{{category.get_absolute_url}}">{{ category.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<div>
    <h1>Top 5 viewed pages</h1>
    <ul>
        {% for page in pages %}
        <li>
            <a href="{{page.url}}">{{ page.titulo }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}
{% block body_end_block %}
<div>
    <img src="{% static 'img/gatoprogramador.jpg' %}" alt="My image" width="50%">
</div>
{% endblock %}

</html>